general:
  main_file_path: ../data/data.csv
  bureau_file_path: ../data/bureau.csv
  bureaubal_file_path: ../data/bureau_balance.csv
  prevapp_file_path: ../data/previous_application.csv
  credit_card_path: ../data/credit_card_balance.csv
  installments_path: ../data/installments_payments.csv
  pos_cash_path: ../data/POS_CASH_balance.csv
  label: TARGET
  ID_feature: SK_ID_CURR
  primary_metric: roc_auc
  threshold: .5
  cv_splits: 5
  resampling_type: under # under, over, none
  resampling_strategy: .3

preprocessing:
  keep_features: [
      # data.csv (application_train.csv)
      CODE_GENDER,
      FLAG_OWN_CAR,
      AMT_INCOME_TOTAL,
      AMT_CREDIT,
      AMT_ANNUITY,
      REGION_POPULATION_RELATIVE,
      DAYS_BIRTH,
      DAYS_EMPLOYED,
      DAYS_REGISTRATION,
      DAYS_ID_PUBLISH,
      FLAG_WORK_PHONE,
      OCCUPATION_TYPE,
      NAME_HOUSING_TYPE,
      CNT_FAM_MEMBERS,
      REGION_RATING_CLIENT,
      ORGANIZATION_TYPE,
      EXT_SOURCE_1,
      EXT_SOURCE_2,
      EXT_SOURCE_3,
      DAYS_LAST_PHONE_CHANGE,
      AMT_REQ_CREDIT_BUREAU_YEAR,
      FLAG_DOCUMENT_3,
      HOUR_APPR_PROCESS_START,
      OWN_CAR_AGE,
      APARTMENTS_AVG,

      # bureau.csv
      CREDIT_CLOSED_CNT_SUM,
      CREDIT_ACTIVE_CNT_SUM,
      DAYS_CREDIT_MEAN,
      DAYS_CREDIT_ENDDATE_MEAN,
      AMT_CREDIT_SUM_MEAN,
      AMT_CREDIT_SUM_DEBT_MEAN,
      AMT_CREDIT_SUM_DEBT_STD,
      AMT_CREDIT_SUM_LIMIT_MEAN,
      DAYS_CREDIT_UPDATE_MIN,
      DAYS_ENDDATE_FACT_MEAN,
      CREDIT_TYPE_CONSUMER_SUM,
      CREDIT_TYPE_NOT_CONSUMER_SUM,

      # bureau_balance.csv
      OLDEST_BALANCE_MONTH_MIN,

      # previous_application.csv
      AMT_DOWN_PAYMENT_MEAN,
      CNT_CONTSTATUS_APPROVED_SUM,
      CNT_CONTSTATUS_REFUSED_SUM,
      CNT_CONTSTATUS_CANCELED_SUM,
      YIELD_SCORE_MEAN,
      CNT_PAYMENT_MEAN,
      CNT_PAYMENT_STD,
      AMT_APPLICATION_MEAN,
      APPLICATION_RATIO_MEAN,
      TOP_GOODS_CATEGORY,
      RATE_DOWN_PAYMENT_MEAN,
      DAYS_FIRST_DUE_MEAN,

      # credit_card_balance.csv
      AMT_CREDIT_LIMIT_ACTUAL_MEAN,
      AMT_BALANCE_MEAN,
      CNT_INSTALMENT_MATURE_CUM_MAX,
      BALANCE_LIMIT_RATIO_MEAN,

      # installments_payments.csv
      PAYMENT_DIFF_MEAN,
      PAYMENT_DIFF_STD,
      LATE_DAYS_MEAN,
      LATE_DAYS_MAX,
      AMT_PAYMENT_SUM,

      # POS_CASH_balance.csv
      SK_DPD_MEAN,
      SK_DPD_DEF_MAX,
      MONTHS_BALANCE_MIN,
      MONTHS_BALANCE_MAX,
      MONTHS_BALANCE_COUNT,

      # Synthetic features
      OVERFINANCE_AMOUNT,
      NAME_FAMILY_STATUS_Married,
      EXPECTED_TERM,
      EST_TOTAL_REPAID,
      PROFIT_AMOUNT,
      INCOME_PER_YEAR_EMPLOYED,
    ]
  value_mappings:
    CODE_GENDER:
      F: 1
      M: 0
      XNA: 0
    FLAG_OWN_CAR:
      Y: 1
      N: 0
    DAYS_EMPLOYED:
      365243: NaN
  missing_handling: # 'drop', 'mean', 'median', 'mode', 'prior', or specific value
    # data.csv (application_train.csv)
    DAYS_LAST_PHONE_CHANGE: mode
    AMT_REQ_CREDIT_BUREAU_YEAR: mean
    EXT_SOURCE_1: -1
    EXT_SOURCE_2: -1
    EXT_SOURCE_3: -1
    CNT_FAM_MEMBERS: mean
    AMT_ANNUITY: mean
    OCCUPATION_TYPE: Unknown
    HOUR_APPR_PROCESS_START: mode
    NAME_HOUSING_TYPE: mode
    DAYS_EMPLOYED: mean

    # bureau.csv
    CREDIT_CLOSED_CNT_SUM: 0
    CREDIT_ACTIVE_CNT_SUM: 0
    DAYS_CREDIT_MEAN: mean
    DAYS_CREDIT_ENDDATE_MEAN: mean
    AMT_CREDIT_SUM_MEAN: mean
    AMT_CREDIT_SUM_DEBT_MEAN: mean
    AMT_CREDIT_SUM_DEBT_STD: mean
    AMT_CREDIT_SUM_LIMIT_MEAN: mean
    DAYS_CREDIT_UPDATE_MIN: mean
    DAYS_ENDDATE_FACT_MEAN: mean
    CREDIT_TYPE_CONSUMER_SUM: mean
    CREDIT_TYPE_NOT_CONSUMER_SUM: mean

    # bureau_balance.csv
    OLDEST_BALANCE_MONTH_MIN: 1

    # previous_application.csv
    AMT_DOWN_PAYMENT_MEAN: mean
    CNT_CONTSTATUS_APPROVED: 0
    CNT_CONTSTATUS_REFUSED: 0
    CNT_CONTSTATUS_CANCELED: 0
    YIELD_SCORE_MEAN: mean
    CNT_CONTSTATUS_APPROVED_SUM: 0
    CNT_CONTSTATUS_REFUSED_SUM: 0
    CNT_CONTSTATUS_CANCELED_SUM: 0
    CNT_PAYMENT_MEAN: mean
    CNT_PAYMENT_STD: mean
    AMT_APPLICATION_MEAN: mean
    APPLICATION_RATIO_MEAN: mean
    TOP_GOODS_CATEGORY: Unknown
    RATE_DOWN_PAYMENT_MEAN: mean
    DAYS_FIRST_DUE_MEAN: mean

    # credit_card_balance.csv
    AMT_CREDIT_LIMIT_ACTUAL_MEAN: -1
    AMT_BALANCE_MEAN: -1
    CNT_INSTALMENT_MATURE_CUM_MAX: -1
    BALANCE_LIMIT_RATIO_MEAN: -1

    # installments_payments.csv
    PAYMENT_DIFF_MEAN: mean
    PAYMENT_DIFF_STD: mean
    LATE_DAYS_MEAN: mean
    LATE_DAYS_MAX: 0
    AMT_PAYMENT_SUM: 0

    # POS_CASH_balance.csv
    SK_DPD_MEAN: 0
    SK_DPD_DEF_MAX: 0
    MONTHS_BALANCE_MIN: mean
    MONTHS_BALANCE_MAX: mean
    MONTHS_BALANCE_COUNT: median

    # Synthetic features
    OVERFINANCE_AMOUNT: mean
    EXPECTED_TERM: mean
    EST_TOTAL_REPAID: mean
    PROFIT_AMOUNT: mean
    INCOME_PER_YEAR_EMPLOYED: mean
    OWN_CAR_AGE: -1
    APARTMENTS_AVG: 0
  # Convert from money to int. Ex. '$1.00' to 1.00
  money_cols: []
  # Combine low frequency categories into a new cateogry. Format of [percent, name]
  comb_low_freq: {}
  clip_features:
    DAYS_CREDIT_UPDATE_MIN: [1, 99]
  type_coercion:
    CREDIT_TYPE_CONSUMER_SUM: int
    CREDIT_TYPE_NOT_CONSUMER_SUM: int
    CNT_FAM_MEMBERS: int
    DAYS_LAST_PHONE_CHANGE: int
    OWN_CAR_AGE: int

encoding:
  numerical_scale_cols: []
  onehot_cols: []
  freq_cols: []
  target_cols: [
    OCCUPATION_TYPE,
    ORGANIZATION_TYPE,
    NAME_HOUSING_TYPE,
    TOP_GOODS_CATEGORY
  ]
  ordinal_cols: []
  binned_cols: []

model_configs:
  dummy_classifier:
    search_type:
    baseline: true
    param_grid: {}

  logistic_regression:
    search_type: grid
    baseline: true
    param_grid:
      model__C: [0.01, 0.1]
      model__penalty: [l2]
      model__solver: [lbfgs]
      model__class_weight: [balanced]

  random_forest:
    search_type: random
    baseline: false
    n_iter: 35
    param_grid:
      model__max_depth: [5, 6, 8, 10]
      model__min_samples_split: [10, 50, 75, 100]
      model__min_samples_leaf: [1, 4, 8, 10, 20]
      model__max_leaf_nodes: [20, 40, 80, 100]
      model__n_estimators: [100, 130, 170, 200]
      model__max_samples: [0.15, 0.2, 0.3, 0.5]
      model__max_features: [sqrt, log2, 0.5]
      model__criterion: [gini, entropy]
      model__class_weight: [balanced]

  lightgbm:
    search_type: random
    baseline: false
    n_iter: 100
    param_grid:
      model__max_depth: [5, 6, 7, 8, 9]
      model__n_estimators: [150, 250, 350, 450, 500, 550]
      model__learning_rate: [0.01, 0.03, 0.05, 0.06]
      model__num_leaves: [15, 20, 30, 50, 70]
      model__min_child_samples: [20, 50, 100, 125]
      model__min_split_gain: [0.01, 0.1, 0.5, 1]
      model__subsample: [0.5, 0.6, 0.75, 0.9]
      model__bagging_freq: [0, 1, 5, 7]
      model__colsample_bytree: [0.5, 0.6, 0.8, 1]
      model__reg_alpha: [0.1, 1, 5, 10]
      model__reg_lambda: [0.5, 1, 5, 10]
      model__class_weight: [balanced]
